version: '3'

services:
  frontend:
    build: ./frontend
    image: frontend-exercise:2.5
    ports:
      - 5000:5000
    container_name: frontend-example
  backend:
    build: ./backend
    image: backend-exercise:2.5
    ports:
      - 8000:8000
    volumes:
      - ./backend/logs.txt:/backend-example-docker/logs.txt
    container_name: backend-example
    networks:
      - redis
    environment:
      - REDIS=cache
      - REDIS_PORT=6379
  cache:
    image: redis
    container_name: redis-cache
    restart: unless-stopped
    networks:
      - redis

networks:
  redis: