version: '3'

services:
  frontend:
    build: ./frontend
    image: frontend-exercise:2.3
    ports:
      - 5000:5000
    container_name: frontend-example
  backend:
    build: ./backend
    image: backend-exercise:2.3
    ports:
      - 8000:8000
    volumes:
      - ./backend/logs.txt:/backend-example-docker/logs.txt
    container_name: backend-example
